import "./globals.css";

import localFont from "next/font/local";
import { type FC, type ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import Providers from "../providers";

const satoshi = localFont({
    src: [
        {
            path: "../../../public/fonts/Satoshi-Variable.ttf",
            style: "normal",
        },
        {
            path: "../../../public/fonts/Satoshi-VariableItalic.ttf",
            style: "italic",
        },
    ],
    display: "swap",
    variable: "--font-satoshi",
});

export const metadata = {
    title: "Greenfield School",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <html lang="en">
            <body className={`font-satoshi ${satoshi.variable}`}>
                <Providers>{children}</Providers>
                <Toaster position="top-center" reverseOrder={false} />
            </body>
        </html>
    );
};

export default RootLayout;
