import "./globals.css";

import type { Metadata } from "next";
import Provider from "./_trpc/Provider";

export const metadata: Metadata = {
    title: "Greenfield School",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
