import "../globals.css";

import type { FC } from "react";
import { I18nProviderClient } from "@/locales/client";
import type { Metadata } from "next";
import Providers from "@/contexts";
import React from "react";
import { getStaticParams } from "@/locales/server";
import localFont from "next/font/local";
import { notFound } from "next/navigation";
import { setStaticParamsLocale } from "next-international/server";

export const metadata: Metadata = {
  title: "Greenfield School",
  description: "Generated by create next app",
};

const satoshiFont = localFont({
  src: [
    {
      path: "../../../public/fonts/Satoshi-Variable.ttf",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Satoshi-VariableItalic.ttf",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-satoshi",
});

export const generateStaticParams = (): ReturnType<typeof getStaticParams> =>
  getStaticParams();
  
type Props = {
  params: { locale: string };
  children: React.ReactNode;
};
const LocaleLayout: FC<Props> = async ({ children, params: { locale } }) => {  
  setStaticParamsLocale(locale);

  return (
    <html lang={locale}>
      <body className={`${satoshiFont.variable} font-satoshi`}>
        <I18nProviderClient locale={locale}>
          <Providers>{children}</Providers>
        </I18nProviderClient>
      </body>
    </html>
  );
};

export default LocaleLayout;
